import {run} from './store.mjs';

// Editorial starting areas from the existing OSM-attributed directory. These are
// checkpoints, not surveyed entrances or navigable trail segments.
export const ADVENTURE_SEEDS = [
 {id:'almaty-medeu-shymbulak',cityId:'almaty',title:'От Медеу к базовой зоне Шымбулака',description:'Коллекция двух горных локаций: Медеу и базовая зона Шымбулака. Между точками не задана пешеходная тропа: способ доступа, режим работы и возможную стоимость уточняйте отдельно. Награда не зависит от скорости или способа подъёма.',kind:'mountain',difficulty:'moderate',cautions:'Пилотный черновик, прохождение отключено. Оператор должен проверить безопасные общедоступные точки, ограничения и условия доступа. Перед поездкой проверяйте погоду и официальные предупреждения. Не двигайтесь по прямой линии карты, не выходите на склоны, закрытые участки и неподготовленные тропы. Отметки 1691 м и около 2260 м относятся к локациям, а не к GPS-измерению.',sourceUrls:['https://kazakhstan.travel/ru/attractions/399','https://kazakhstan.travel/ru/attractions/398','https://www.gov.kz/memleket/entities/emer/press/news/details/1138144?lang=ru'],status:'draft',statusReason:'Нужна проверка доступных точек на месте и условий доступа оператором. Маршрут не открыт.',xp:120,checkpoints:[{title:'Медеу: отметка локации 1691 м',lng:77.05889,lat:43.15789,radius:120,altitudeM:1691},{title:'Базовая зона Шымбулака: около 2260 м',lng:77.08142,lat:43.12827,radius:120,altitudeM:2260}]},
 {id:'almaty-park-walk',cityId:'almaty',title:'Алматы: истории парка',description:'Неспешная прогулка по открытым дорожкам парка: найди две знакомые городские детали.',kind:'urban',difficulty:'easy',cautions:'Только днём и по открытым пешеходным дорожкам. Не заходи в здания, за ограждения и на закрытую территорию. При закрытом проходе отложи задание.',sourceUrls:['https://www.openstreetmap.org/way/208493040','https://www.openstreetmap.org/way/50648292'],status:'open',statusReason:'Городской пилот: отмечаются открытые пешеходные зоны; текущий доступ проверяйте на месте.',xp:80,checkpoints:[{title:'Дорожка парка 28 гвардейцев-панфиловцев',lng:76.9538,lat:43.2580,radius:70,altitudeM:null},{title:'Собор снаружи, с парковой дорожки',lng:76.9531145,lat:43.2587859,radius:70,altitudeM:null}]},
 {id:'astana-river-walk',cityId:'astana',title:'Астана: образы набережной',description:'Прогулка по доступным дорожкам парка Ататюрка к скульптуре Жер-ана.',kind:'urban',difficulty:'easy',cautions:'Выполняй днём. Учитывай ветер и гололёд. Не выходи на лёд, не спускайся к воде, не поднимайся на скульптуры. При закрытом проходе отложи задание.',sourceUrls:['https://www.openstreetmap.org/way/1460702136','https://www.openstreetmap.org/node/4109068593'],status:'open',statusReason:'Городской пилот: точки из карты, доступные подходы уточняются на месте.',xp:80,checkpoints:[{title:'Парк Ататюрка: открытая дорожка',lng:71.4318117,lat:51.152019,radius:100,altitudeM:null},{title:'Жер-ана: вид с дорожки',lng:71.4317199,lat:51.1533831,radius:80,altitudeM:null}]},
];
export const TERRITORY_SEEDS = [
 {id:'almaty-panfilov',cityId:'almaty',title:'Парк 28 гвардейцев-панфиловцев',description:'Виртуальная командная зона на открытых дорожках парка. Никаких прав на реальную территорию.',lng:76.9538,lat:43.2580,radius:180},
 {id:'almaty-central-park',cityId:'almaty',title:'У входа в Центральный парк',description:'Виртуальная зона у общедоступного входа. При закрытом проходе отложи визит.',lng:76.9684,lat:43.2620,radius:150},
 {id:'astana-ataturk',cityId:'astana',title:'Парк Ататюрка',description:'Виртуальная зона открытых дорожек парка. Не выходи к воде или на лёд.',lng:71.4318117,lat:51.152019,radius:180},
 {id:'astana-opera-square',cityId:'astana',title:'Площадь у Астана Опера',description:'Виртуальная зона общедоступной пешеходной площади. Вход в театр не нужен.',lng:71.4106104,lat:51.1346692,radius:130},
];

export function* seedAdventures(now = Date.now()) {
 for (const r of ADVENTURE_SEEDS) yield run('INSERT INTO adventure_routes(id,city_id,title,description,kind,difficulty,cautions,source_urls,checkpoints_json,status,status_reason,created_at,updated_at,version,xp) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$12,1,$13) ON CONFLICT(id) DO NOTHING',[r.id,r.cityId,r.title,r.description,r.kind,r.difficulty,r.cautions,JSON.stringify(r.sourceUrls),JSON.stringify(r.checkpoints),r.status,r.statusReason,now,r.xp]);
 for (const z of TERRITORY_SEEDS) yield run("INSERT INTO territory_zones(id,city_id,title,description,lng,lat,radius,status,created_at,updated_at,version) VALUES($1,$2,$3,$4,$5,$6,$7,'active',$8,$8,1) ON CONFLICT(id) DO NOTHING",[z.id,z.cityId,z.title,z.description,z.lng,z.lat,z.radius,now]);
}
