import {VERSION} from '../src/version.mjs';
import {contentSecurityPolicy,mapConfiguration} from '../src/http-policy.mjs';
import {readFile,writeFile,cp,mkdir,rm} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {resolve,dirname} from 'node:path';
import {createRequire} from 'node:module';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'..');
const origin=process.env.CITYQUEST_API_ORIGIN;
if(!origin)throw new Error('Set CITYQUEST_API_ORIGIN=https://your-api.example (no path) before building. No default remote endpoint is embedded.');
const url=new URL(origin);
if(url.protocol!=='https:'||url.username||url.password||url.pathname!=='/'||url.search||url.hash)throw new Error('CITYQUEST_API_ORIGIN must be an HTTPS origin without credentials, path, query or fragment');
const require=createRequire(resolve(root,'mobile/package.json'));const {build}=require('esbuild');
const out=resolve(root,'mobile/www');await rm(out,{recursive:true,force:true});await mkdir(out,{recursive:true});await cp(resolve(root,'public'),out,{recursive:true});
const csp=contentSecurityPolicy({...mapConfiguration(process.env),apiOrigin:url.origin,native:true}).replace("; frame-ancestors 'none'",'');
let html=await readFile(resolve(out,'index.html'),'utf8');
html=html.replace('<meta charset="UTF-8">',`<meta charset="UTF-8"><meta http-equiv="Content-Security-Policy" content="${csp}">`).replace('src="/app.js"','src="/mobile.js"');
await writeFile(resolve(out,'index.html'),html);
await build({entryPoints:[resolve(root,'mobile/src/entry.js')],outfile:resolve(out,'mobile.js'),bundle:true,format:'esm',platform:'browser',target:['chrome109','safari16.4'],minify:true,define:{__CITYQUEST_API_BASE__:JSON.stringify(url.origin)},legalComments:'eof'});
for(const file of ['app.js','map.js','platform.js','companion.js','adventures.js','team-presence.js','sw.js'])await rm(resolve(out,file),{force:true});
await writeFile(resolve(out,'build-info.json'),JSON.stringify({version:VERSION,apiOrigin:url.origin,bundledAssets:true},null,2)+'\n');
console.log('Bundled shared web UI for Android/iOS. API origin: '+url.origin);
