import {parseQuestMetadata,publicQuest} from './quest-metadata.mjs';
import {VERSION} from './version.mjs';
import {inspectEncryptionSync,requireValidEncryption} from './key-check.mjs';
import {createWorkTracker} from './lifecycle.mjs';
import http from 'node:http';
import {createPasswordService} from './passwords.mjs';
import {publicProductPolicy,PHOTO_MEDIA_LIMITS} from './product-policy.mjs';
import {setBodyPolicy} from './http-body.mjs';
import {createAdmission,holdResponseSlot,contentSecurityPolicy} from './http-policy.mjs';
import {readFile,stat} from 'node:fs/promises';
import {existsSync} from 'node:fs';
import {resolve,extname,dirname,sep} from 'node:path';
import {fileURLToPath} from 'node:url';
import {randomBytes} from 'node:crypto';
import {AsyncLocalStorage} from 'node:async_hooks';
import {performance} from 'node:perf_hooks';
import {openDb,transaction} from './db.mjs';
import {id,hash,passwordHash,fail,text,number,choice,point,distance,cell,normalizeEmail,normalizeCode,city} from './domain.mjs';
import {CITIES,DEFAULT_CITY} from './cities.mjs';
import {importOsm,osmQuery} from './osm.mjs';
import {runtimeConfig,clientIp} from './runtime.mjs';
import {createAuth,readJson} from './auth.mjs';
import {appendAudit,verifyAudit,sealLegacyAudit,consumeRate,pruneRateLimits} from './security.mjs';
import {createFeatureStore} from './features/store.mjs';
import {createPetRoutes,prunePetData} from './features/pet-routes.mjs';
import {createBillingRoutes} from './features/billing-routes.mjs';
import {createAdventureRoutes} from './features/adventure-routes.mjs';
import {createPhotoRoutes,prunePhotoUsage} from './features/photo-routes.mjs';
import {createListRoutes} from './features/list-routes.mjs';
const publicRoot=resolve(dirname(fileURLToPath(import.meta.url)),'../public');
const publicOrg=o=>{const {owner_id,...rest}=o;return rest;};
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.mjs':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.webmanifest':'application/manifest+json'};
export function createApp({db,secure,origin,env=process.env,keys,petFetchImpl,passwordService}={}) {
 const ownsDb=!db;db??=openDb();
 let cfg;
 try{
  cfg=runtimeConfig(db,{env,secure,origin,keys});
  requireValidEncryption(inspectEncryptionSync(db,cfg.keys.encryptionKey,{sample:true}));
  const integrity=sealLegacyAudit(db,cfg.keys.auditKey);if(!integrity.ok)throw new Error('Audit integrity verification failed at startup');
 }catch(e){if(ownsDb)db.close();throw e;}
 const contexts=new AsyncLocalStorage();
 const started=Date.now(),metrics={requests:0,errors:0,statuses:{},durations:[]};let draining=false,cleanupRunning=false,closing;const work=createWorkTracker();
 function throttle(key,limit=30,windowMs=60000){const r=consumeRate(db,hash(key),{limit,windowMs,maxKeys:cfg.rateLimitMaxKeys});if(!r.allowed){const e=new Error('Слишком много попыток. Подождите.');e.status=429;e.retryAfter=Math.max(1,Math.ceil(r.retryAfterMs/1000));throw e;}}
 function audit(actor,action,target,metadata={}){return appendAudit(db,{actor,action,target,metadata,requestId:contexts.getStore()?.requestId||'operator'},cfg.keys.auditKey);}
 passwordService??=createPasswordService({concurrency:cfg.passwordKdfConcurrency});const admission=createAdmission(cfg.http);
 const auth=createAuth({db,cfg,throttle,audit,passwordService}),{required,publicUser}=auth;
 const featureStore=createFeatureStore({db,cfg,dialect:'sqlite',audit:(_tx,...args)=>audit(...args)});
 const lists=createListRoutes({store:featureStore});
 const pet=createPetRoutes({store:featureStore,cfg,env,fetchImpl:petFetchImpl}),billing=createBillingRoutes({store:featureStore,cfg,env});
 const adventures=createAdventureRoutes({store:featureStore,cfg,env}),photos=createPhotoRoutes({store:featureStore,cfg,env});
 async function readAuthorizedJson(req,user){const body=await readJson(req);if(user){const fresh=auth.session(req);if(!fresh||fresh.session_id!==user.session_id||fresh.role!==user.role||fresh.session_mfa_verified!==user.session_mfa_verified||fresh.mfa_enabled!==user.mfa_enabled)fail('Доступ изменился. Войдите заново.',401);}return body;}
 function validAssignee(value){if(!value)return null;if(typeof value!=='string'||!/^[a-zA-Z0-9-]+$/.test(value)||value.length>80)fail('Пользователь не найден');if(!db.prepare('SELECT id FROM users WHERE id=? AND disabled=0').get(value))fail('Пользователь не найден');return value;}
 function orgPermission(user,org){required(user,['admin','business']);if(!org)fail('Организация не найдена',404);if(user.role!=='admin'&&org.owner_id!==user.id)fail('Это чужая организация',403);}
 function questPermission(user,q){required(user,['admin','business']);if(!q)fail('Квест не найден',404);if(user.role!=='admin'&&q.owner_id!==user.id)fail('Это чужой квест',403);}
 function insertObject(table,obj){const names=Object.keys(obj);db.prepare(`INSERT INTO ${table}(${names.join(',')}) VALUES(${names.map(()=>'?').join(',')})`).run(...names.map(n=>obj[n]));}
 function updateVersioned(table,old,b,obj){if(!Number.isSafeInteger(b.version)||b.version!==old.version)fail('Запись изменена. Обновите данные перед сохранением.',409);const values={...obj,version:old.version+1,updated_at:Date.now()},names=Object.keys(values);const r=db.prepare(`UPDATE ${table} SET ${names.map(n=>n+'=?').join(',')} WHERE id=? AND version=?`).run(...names.map(n=>values[n]),old.id,old.version);if(!r.changes)fail('Конфликт изменений. Обновите данные.',409);return {...old,...values};}
 function parseOrg(b,user,old){const c=city(b.city_id||old?.city_id||DEFAULT_CITY);point(b.lng,b.lat,c.id);if(old&&c.id!==old.city_id)fail('Для другого города создайте новую карточку');const status=user.role==='admin'?choice(b.status||'approved',['pending','approved','rejected'],'статус'):'pending';return {city_id:c.id,name:text(b.name,'Название',160),category:text(b.category||'other','Категория',60),lng:b.lng,lat:b.lat,address:text(b.address||'','Адрес',250,0),description:text(b.description||'','Описание',2000,0),status,owner_id:user.role==='admin'?validAssignee(b.owner_id):user.id};}
 function parseQuest(b,user,old){const c=city(b.city_id||old?.city_id||DEFAULT_CITY);point(b.lng,b.lat,c.id);if(old&&c.id!==old.city_id)fail('Нельзя переместить существующий квест в другой город');const orgId=b.organization_id||null;if(orgId&&(typeof orgId!=='string'||!/^[a-zA-Z0-9-]+$/.test(orgId)||orgId.length>80))fail('Организация не найдена');const org=orgId?db.prepare('SELECT * FROM organizations WHERE id=?').get(orgId):null;if(orgId&&!org)fail('Организация не найдена');if(org&&org.city_id!==c.id)fail('Организация находится в другом городе');if(user.role==='business')orgPermission(user,org);
  const status=user.role==='admin'?choice(b.status||'draft',['draft','pending','published','archived'],'статус'):choice(b.status||'pending',['draft','pending'],'статус');if(status==='published'&&org&&org.status!=='approved')fail('Сначала одобрите организацию');
  const verification=choice(b.verification||'checkin',['checkin','code','token'],'проверка');let codeHash=null;if(verification==='code'){if(b.code)codeHash=hash(normalizeCode(text(b.code,'Код',64,4)));else if(old?.verification==='code')codeHash=old.code_hash;else fail('Укажите код от 4 символов');}
  const scope=choice(b.scope||'public',['public','personal'],'тип квеста'),assigned=user.role==='admin'?validAssignee(b.assigned_to):(old?.assigned_to??null);if(assigned&&scope!=='personal')fail('Назначать игроку можно только индивидуальный квест');
  const starts=b.starts_at==null||b.starts_at===''?null:Math.round(number(b.starts_at,'Начало',0,9000000000000)),ends=b.ends_at==null||b.ends_at===''?null:Math.round(number(b.ends_at,'Окончание',0,9000000000000));if(starts!==null&&ends!==null&&ends<=starts)fail('Окончание должно быть после начала');
  const cap=b.max_completions==null||b.max_completions===''?null:Math.round(number(b.max_completions,'Лимит наград',1,1000000));if(old&&cap!==null&&db.prepare('SELECT count(*) n FROM completions WHERE quest_id=?').get(old.id).n>cap)fail('Лимит меньше уже выданных наград');
  return {city_id:c.id,title:text(b.title,'Название',160),description:text(b.description,'Описание',3000,10),lng:b.lng,lat:b.lat,radius:Math.round(number(b.radius??150,'Радиус',30,500)),xp:Math.round(number(b.xp??100,'Опыт',10,1000)),scope,verification,code_hash:codeHash,status,organization_id:orgId,assigned_to:assigned,goal:Math.round(number(b.goal??20,'Общая цель',1,10000)),starts_at:starts,ends_at:ends,max_completions:cap,...parseQuestMetadata(b,old)};
 }
 async function route(req,res,url){const p=url.pathname,method=req.method,user=auth.session(req),ip=clientIp(req,cfg.trustProxy);const cityId=city(url.searchParams.get('city')||DEFAULT_CITY).id;
  if(p==='/api/health'&&method==='GET')return {ok:true,version:VERSION,deployment:'single-instance-sqlite'};
  if(p==='/api/auth/sso/config'&&method==='GET')return {enabled:false};
  if(p==='/api/ready'&&method==='GET'){if(draining)fail('Сервис завершает работу',503);db.prepare('SELECT 1').get();return {ok:true,schema:db.prepare('PRAGMA user_version').get().user_version};}
  if(p==='/api/config'&&method==='GET')return {city:CITIES[cityId],cities:Object.values(CITIES),mapStyle:cfg.mapStyle,productPolicy:publicProductPolicy(cfg.productPolicy),contacts:cfg.contacts,localMapAssets:['maplibre-gl.js','maplibre-gl.css','three.module.js','three.core.js'].every(f=>existsSync(resolve(publicRoot,'vendor',f))),bounds:CITIES[cityId].bounds,organizations:db.prepare("SELECT count(*) n FROM organizations WHERE status='approved' AND city_id=?").get(cityId).n,osmImport:JSON.parse(db.prepare('SELECT value FROM meta WHERE key=?').get(`osm_import_${cityId}`)?.value||'null'),adminConfigured:!!db.prepare("SELECT id FROM users WHERE role='admin' AND disabled=0").get(),enterprisePilot:true};
  const authResult=await auth.handle(req,res,url,user,ip);if(authResult!==undefined)return authResult;
  const featureContext={db,cfg,req,res,url,path:p,method,user,ip,cityId,auth,required,throttle,readBody:()=>readAuthorizedJson(req,user)};
  const petResult=await pet(featureContext);if(petResult!==undefined)return petResult;
  const billingResult=await billing(featureContext);if(billingResult!==undefined)return billingResult;
  const adventureResult=await adventures(featureContext);if(adventureResult!==undefined)return adventureResult;
  const photoResult=await photos(featureContext);if(photoResult!==undefined||res.writableEnded)return photoResult;
  const listResult=await lists(featureContext);if(listResult!==undefined)return listResult;
  if(p==='/api/location'&&method==='POST'){
   required(user);throttle(`geo:${user.id}`,30);const b=await readAuthorizedJson(req,user),c=city(b.city_id||DEFAULT_CITY);point(b.lng,b.lat,c.id);number(b.accuracy,'Точность GPS',0,150);number(b.timestamp,'Время GPS',Date.now()-120000,Date.now()+15000);const old=db.prepare('SELECT * FROM positions WHERE user_id=?').get(user.id),now=Date.now();
   if(old&&now-old.updated_at<120000&&distance(old,b)>Math.max(300,(now-old.updated_at)/1000*25))fail('Слишком резкое перемещение. Дождитесь точного GPS.');
   transaction(db,()=>{db.prepare('INSERT INTO positions(user_id,lng,lat,accuracy,updated_at,city_id) VALUES(?,?,?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET lng=excluded.lng,lat=excluded.lat,accuracy=excluded.accuracy,updated_at=excluded.updated_at,city_id=excluded.city_id').run(user.id,b.lng,b.lat,b.accuracy,now,c.id);db.prepare('INSERT OR IGNORE INTO explored(user_id,cell,created_at,city_id) VALUES(?,?,?,?)').run(user.id,cell(b.lng,b.lat),now,c.id);});return {ok:true,cell:cell(b.lng,b.lat),city_id:c.id,cells_total:db.prepare('SELECT count(*) AS n FROM explored WHERE user_id=? AND city_id=?').get(user.id,c.id).n};
  }
  if(p==='/api/location'&&method==='DELETE'){required(user);transaction(db,()=>{db.prepare('DELETE FROM positions WHERE user_id=?').run(user.id);db.prepare('UPDATE members SET share_location=0 WHERE user_id=?').run(user.id);audit(user.id,'privacy.position_deleted',user.id);});return {ok:true};}
  if(p==='/api/explored'&&method==='DELETE'){required(user);transaction(db,()=>{db.prepare('DELETE FROM explored WHERE user_id=? AND city_id=?').run(user.id,cityId);db.prepare('DELETE FROM positions WHERE user_id=? AND city_id=?').run(user.id,cityId);audit(user.id,'privacy.explored_deleted',user.id,{city_id:cityId});});return {ok:true};}
  const complete=p.match(/^\/api\/quests\/([a-zA-Z0-9-]+)\/complete$/);
  if(complete&&method==='POST'){
   required(user);throttle(`complete:${user.id}`,20);const b=await readAuthorizedJson(req,user);
   const result=transaction(db,()=>{const q=db.prepare("SELECT * FROM quests WHERE id=? AND status='published'").get(complete[1]);if(!q||q.assigned_to&&q.assigned_to!==user.id)fail('Квест недоступен',404);
    if(db.prepare('SELECT quest_id FROM completions WHERE user_id=? AND quest_id=?').get(user.id,q.id))return {alreadyCompleted:true,xp:0};
    const now=Date.now();if(q.starts_at&&q.starts_at>now||q.ends_at!==null&&q.ends_at<=now)fail('Квест сейчас недоступен по расписанию',409);if(q.max_completions!==null&&db.prepare('SELECT count(*) n FROM completions WHERE quest_id=?').get(q.id).n>=q.max_completions)fail('Лимит наград исчерпан',409);
    const pos=db.prepare('SELECT * FROM positions WHERE user_id=?').get(user.id);if(!pos||pos.city_id!==q.city_id||now-pos.updated_at>90000)fail('Обновите GPS в городе квеста перед подтверждением');const meters=distance(pos,q);if(meters>q.radius+Math.min(pos.accuracy,30))fail(`До места около ${Math.round(meters)} м. Подойдите ближе.`);
    if(q.verification==='code'&&hash(normalizeCode(b.code))!==q.code_hash)fail('Неверный код подтверждения');
    if(q.verification==='token'){const code=normalizeCode(b.code);if(!/^[A-F0-9]{24}$/.test(code))fail('Неверный одноразовый код');const token=db.prepare('SELECT * FROM reward_tokens WHERE quest_id=? AND token_hash=? AND redeemed_at IS NULL AND revoked_at IS NULL AND expires_at>?').get(q.id,hash(code),now);if(!token)fail('Код недействителен, использован или истёк');const consumed=db.prepare('UPDATE reward_tokens SET redeemed_at=?,redeemed_by=? WHERE id=? AND redeemed_at IS NULL AND revoked_at IS NULL').run(now,user.id,token.id);if(!consumed.changes)fail('Код уже использован',409);}
    db.prepare('INSERT INTO completions(user_id,quest_id,xp,created_at) VALUES(?,?,?,?)').run(user.id,q.id,q.xp,now);db.prepare('UPDATE users SET xp=xp+? WHERE id=?').run(q.xp,user.id);audit(user.id,'quest.complete',q.id,{city_id:q.city_id,xp:q.xp,verification:q.verification});return {alreadyCompleted:false,xp:q.xp};});return {...result,user:publicUser(db.prepare('SELECT * FROM users WHERE id=?').get(user.id))};
  }
  if(p==='/api/manage/organizations'&&method==='POST'){required(user,['business','admin']);const b=await readAuthorizedJson(req,user),obj={id:id(),...parseOrg(b,user),source:'manual',created_at:Date.now(),updated_at:Date.now(),version:1};transaction(db,()=>{insertObject('organizations',obj);audit(user.id,'organization.create',obj.id,{city_id:obj.city_id});});return {item:obj};}
  const editOrg=p.match(/^\/api\/manage\/organizations\/([a-zA-Z0-9-]+)$/);
  if(editOrg&&method==='PATCH'){required(user,['business','admin']);const b=await readAuthorizedJson(req,user);return transaction(db,()=>{const old=db.prepare('SELECT * FROM organizations WHERE id=?').get(editOrg[1]);orgPermission(user,old);const obj=parseOrg({...old,...b},user,old),item=updateVersioned('organizations',old,b,obj);if(obj.status!=='approved')db.prepare("UPDATE quests SET status='pending',version=version+1,updated_at=? WHERE organization_id=? AND status='published'").run(Date.now(),old.id);audit(user.id,'organization.update',old.id,{city_id:old.city_id,version:item.version});return {item};});}
  if(p==='/api/manage/quests'&&method==='POST'){required(user,['business','admin']);const b=await readAuthorizedJson(req,user),obj={id:id(),owner_id:user.id,...parseQuest(b,user),created_at:Date.now(),updated_at:Date.now(),version:1};transaction(db,()=>{insertObject('quests',obj);audit(user.id,'quest.create',obj.id,{city_id:obj.city_id});});return {item:publicQuest(obj)};}
  const editQuest=p.match(/^\/api\/manage\/quests\/([a-zA-Z0-9-]+)$/);
  if(editQuest&&method==='PATCH'){required(user,['business','admin']);const b=await readAuthorizedJson(req,user);return transaction(db,()=>{const q=db.prepare('SELECT * FROM quests WHERE id=?').get(editQuest[1]);questPermission(user,q);const obj=parseQuest({...q,...b},user,q),item=updateVersioned('quests',q,b,obj);if(obj.status!=='published'||obj.verification!=='token')db.prepare('UPDATE reward_tokens SET revoked_at=? WHERE quest_id=? AND redeemed_at IS NULL AND revoked_at IS NULL').run(Date.now(),q.id);audit(user.id,'quest.update',q.id,{city_id:q.city_id,version:item.version});return {item:publicQuest(item)};});}
  const tokens=p.match(/^\/api\/manage\/quests\/([a-zA-Z0-9-]+)\/tokens$/);
  if(tokens&&method==='POST'){required(user,['business','admin']);throttle(`tokens:${user.id}`,20);const b=await readAuthorizedJson(req,user),count=number(b.count??1,'Число кодов',1,20),minutes=number(b.expires_in_minutes??60,'Срок кода, мин',5,1440);if(!Number.isInteger(count)||!Number.isInteger(minutes))fail('Укажите целое число');return transaction(db,()=>{const q=db.prepare('SELECT * FROM quests WHERE id=?').get(tokens[1]);questPermission(user,q);if(user.role==='business')orgPermission(user,db.prepare('SELECT * FROM organizations WHERE id=?').get(q.organization_id));if(q.verification!=='token'||q.status!=='published')fail('Одноразовые коды доступны опубликованному квесту с этой проверкой');const now=Date.now();if(q.ends_at!==null&&q.ends_at<=now)fail('Квест завершён');const expires=Math.min(now+minutes*60000,q.ends_at??Infinity);const issued=[];for(let i=0;i<count;i++){const code=randomBytes(12).toString('hex').toUpperCase(),tid=id();db.prepare('INSERT INTO reward_tokens(id,quest_id,issuer_id,token_hash,created_at,expires_at) VALUES(?,?,?,?,?,?)').run(tid,q.id,user.id,hash(code),now,expires);issued.push({id:tid,code,expires_at:expires});}audit(user.id,'reward.tokens_issued',q.id,{city_id:q.city_id,count});return {tokens:issued};});}
  if(p==='/api/manage/osm'&&method==='POST'){required(user,['admin']);const data=await readAuthorizedJson(req,user);let result;try{result=importOsm(db,data,cityId,{onImported:report=>audit(user.id,'osm.import',cityId,{...report,city_id:cityId})});}catch(e){fail(e.message);}return result;}
  if(p==='/api/manage/osm-query'&&method==='GET'){required(user,['admin']);return {query:osmQuery(cityId)};}
  const role=p.match(/^\/api\/manage\/users\/([a-zA-Z0-9-]+)$/);
  if(role&&method==='PATCH'){required(user,['admin']);const b=await readAuthorizedJson(req,user),target=role[1];if(target===user.id)fail('Нельзя менять свою роль');const old=db.prepare('SELECT * FROM users WHERE id=?').get(target);if(!old)fail('Пользователь не найден',404);const next=choice(b.role||old.role,['player','business','admin'],'роль');if(b.disabled!==undefined&&typeof b.disabled!=='boolean')fail('Некорректный статус аккаунта');const disabled=b.disabled===undefined?old.disabled:b.disabled?1:0;transaction(db,()=>{db.prepare('UPDATE users SET role=?,disabled=? WHERE id=?').run(next,disabled,target);db.prepare('DELETE FROM sessions WHERE user_id=?').run(target);db.prepare('DELETE FROM login_challenges WHERE user_id=?').run(target);audit(user.id,'user.access_updated',target,{role:next,disabled:!!disabled});});return {ok:true};}
  if(p==='/api/team'&&method==='GET'){
   required(user);const team=db.prepare('SELECT t.*,m.share_location FROM teams t JOIN members m ON m.team_id=t.id WHERE m.user_id=?').get(user.id);if(!team)return {team:null};if(team.city_id!==cityId)return {team:null,otherCity:team.city_id};
   const now=Date.now();
   const members=db.prepare('SELECT u.id,u.name,u.xp,m.share_location,p.lng,p.lat,p.updated_at,p.city_id FROM members m JOIN users u ON u.id=m.user_id LEFT JOIN positions p ON p.user_id=u.id AND p.city_id=? WHERE m.team_id=?').all(team.city_id,team.id).map(m=>({id:m.id,name:m.name,xp:m.xp,online:!!m.updated_at&&now-m.updated_at<60000,location:m.share_location&&m.updated_at&&now-m.updated_at<60000?{lng:m.lng,lat:m.lat,expiresInMs:Math.max(0,m.updated_at+60000-now)}:null}));
   const progress=db.prepare("SELECT q.id,q.title,q.goal,count(*) AS completions FROM completions c JOIN quests q ON q.id=c.quest_id JOIN members m ON m.user_id=c.user_id WHERE m.team_id=? AND q.city_id=? AND q.scope='public' AND q.status='published' AND c.created_at>=? AND c.created_at>=m.joined_at GROUP BY q.id").all(team.id,team.city_id,team.created_at);return {team:{...team,invite:team.owner_id===user.id?team.invite:undefined},members,progress};
  }
  if(p==='/api/team'&&method==='POST'){required(user);throttle(`team:${user.id}`,10);const b=await readAuthorizedJson(req,user),c=city(b.city_id||DEFAULT_CITY),team={id:id(),name:text(b.name,'Название команды',60,2),owner_id:user.id,city_id:c.id,invite:randomBytes(6).toString('hex').toUpperCase(),created_at:Date.now()};transaction(db,()=>{if(db.prepare('SELECT user_id FROM members WHERE user_id=?').get(user.id))fail('Сначала выйдите из текущей команды');insertObject('teams',team);db.prepare('INSERT INTO members(user_id,team_id,joined_at) VALUES(?,?,?)').run(user.id,team.id,Date.now());audit(user.id,'team.create',team.id,{city_id:c.id});});return {team};}
  if(p==='/api/team/join'&&method==='POST'){required(user);throttle(`join:${user.id}`,10,600000);const b=await readAuthorizedJson(req,user),c=city(b.city_id||DEFAULT_CITY);return transaction(db,()=>{const team=db.prepare('SELECT * FROM teams WHERE invite=?').get(normalizeCode(b.code));if(!team||team.city_id!==c.id)fail('Команда не найдена в выбранном городе',404);if(db.prepare('SELECT user_id FROM members WHERE user_id=?').get(user.id))fail('Сначала выйдите из текущей команды');if(db.prepare('SELECT count(*) n FROM members WHERE team_id=?').get(team.id).n>=20)fail('В команде уже 20 участников');db.prepare('INSERT INTO members(user_id,team_id,joined_at) VALUES(?,?,?)').run(user.id,team.id,Date.now());audit(user.id,'team.join',team.id,{city_id:c.id});return {ok:true};});}
  if(p==='/api/team/sharing'&&method==='PATCH'){required(user);const b=await readAuthorizedJson(req,user);if(typeof b.enabled!=='boolean')fail('Нужно логическое значение');transaction(db,()=>{db.prepare('UPDATE members SET share_location=? WHERE user_id=?').run(b.enabled?1:0,user.id);audit(user.id,'privacy.team_sharing',user.id,{enabled:b.enabled});});return {ok:true};}
  if(p==='/api/team'&&method==='DELETE'){required(user);transaction(db,()=>{const team=db.prepare('SELECT t.* FROM teams t JOIN members m ON m.team_id=t.id WHERE m.user_id=?').get(user.id);if(!team)return;db.prepare('DELETE FROM members WHERE user_id=?').run(user.id);if(team.owner_id===user.id){const next=db.prepare('SELECT user_id FROM members WHERE team_id=? ORDER BY user_id LIMIT 1').get(team.id);if(next)db.prepare('UPDATE teams SET owner_id=?,invite=? WHERE id=?').run(next.user_id,randomBytes(6).toString('hex').toUpperCase(),team.id);else db.prepare('DELETE FROM teams WHERE id=?').run(team.id);}audit(user.id,'team.leave',team.id,{city_id:team.city_id});});return {ok:true};}
  if(p==='/api/admin/metrics'&&method==='GET'){required(user,['admin']);const d=[...metrics.durations].sort((a,b)=>a-b),at=f=>d[Math.min(d.length-1,Math.floor(d.length*f))]||0;return {admission:admission.snapshot(),uptime_seconds:Math.floor((Date.now()-started)/1000),requests:metrics.requests,errors:metrics.errors,statuses:metrics.statuses,latency_ms:{p50:at(.5),p95:at(.95),p99:at(.99),sample_count:d.length},active_sessions:db.prepare('SELECT count(*) n FROM sessions WHERE expires>? AND last_seen>?').get(Date.now(),Date.now()-cfg.idleMs).n,cities:Object.keys(CITIES).map(c=>({id:c,organizations:db.prepare('SELECT count(*) n FROM organizations WHERE city_id=?').get(c).n,quests:db.prepare('SELECT count(*) n FROM quests WHERE city_id=?').get(c).n})),deployment:'single-instance-sqlite'};}
  if(p==='/api/admin/audit/verify'&&method==='GET'){required(user,['admin']);throttle(`audit-verify:${user.id}`,1,60000);return verifyAudit(db,cfg.keys.auditKey);}
  if(p==='/api/admin/audit'&&method==='GET'){required(user,['admin']);const limit=Math.min(500,Math.max(1,Number(url.searchParams.get('limit'))||100)),before=Math.max(0,Number(url.searchParams.get('before'))||Number.MAX_SAFE_INTEGER);return {items:db.prepare('SELECT id,actor_id,action,target,created_at,metadata,request_id,prev_hash,event_hash FROM audit WHERE id<? ORDER BY id DESC LIMIT ?').all(before,limit)};}
  fail('Маршрут не найден',404);
 }
 const server=http.createServer((req,res)=>contexts.run({requestId:id()},async()=>{
  const doneWork=work.enter(),requestId=contexts.getStore().requestId,start=performance.now();let release;res.setTimeout(cfg.http.responseTimeoutMs,()=>res.destroy());res.setHeader('X-Request-Id',requestId);res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','strict-origin-when-cross-origin');res.setHeader('Permissions-Policy','geolocation=(self), camera=(), microphone=()');res.setHeader('X-Frame-Options','DENY');if(cfg.secure)res.setHeader('Strict-Transport-Security','max-age=31536000');
  res.setHeader('Content-Security-Policy',contentSecurityPolicy(cfg));
  res.on('finish',()=>{const elapsed=Number((performance.now()-start).toFixed(2));metrics.requests++;metrics.statuses[res.statusCode]=(metrics.statuses[res.statusCode]||0)+1;if(res.statusCode>=500)metrics.errors++;metrics.durations.push(elapsed);if(metrics.durations.length>5000)metrics.durations.shift();if(cfg.jsonLogs)console.log(JSON.stringify({event:'http',request_id:requestId,method:req.method,status:res.statusCode,duration_ms:elapsed}));});
  try{
   const url=new URL(req.url,'http://localhost');if(url.pathname.startsWith('/api/')){
    res.setHeader('Cache-Control','no-store');const photoUpload=req.method==='POST'&&url.pathname==='/api/photos',catalogImport=req.method==='POST'&&url.pathname==='/api/manage/osm',upload=photoUpload||catalogImport,bodyLimit=photoUpload?4*Math.ceil(PHOTO_MEDIA_LIMITS.inputBytes/3)+16384:catalogImport?8*1024*1024:cfg.http.jsonBytes;
    setBodyPolicy(req,{maxBytes:bodyLimit,timeoutMs:cfg.http.bodyTimeoutMs});
    if(Number(req.headers['content-length'])>bodyLimit)throw Object.assign(new Error('Запрос слишком большой'),{status:413,closeConnection:true});
    if(!['/api/health','/api/ready'].includes(url.pathname))release=holdResponseSlot(res,admission.enter({upload}));
if(!['/api/health','/api/ready'].includes(url.pathname))throttle(`all:${clientIp(req,cfg.trustProxy)}`,3000);
    if(!['GET','HEAD'].includes(req.method)){if(draining)fail('Сервис завершает работу',503);const expected=cfg.origin||`${cfg.secure?'https':'http'}://${req.headers.host}`;if(req.headers['sec-fetch-site']==='cross-site'||req.headers.origin&&req.headers.origin!==expected)fail('Запрос с другого сайта запрещён',403);if(req.method!=='DELETE'&&!req.headers['content-type']?.startsWith('application/json'))fail('Ожидается application/json',415);}
    const result=await route(req,res,url);if(!res.writableEnded){res.writeHead(200,{'Content-Type':'application/json; charset=utf-8'});res.end(JSON.stringify(result));}
   }else{
    if(!['GET','HEAD'].includes(req.method))fail('Метод не поддерживается',405);let pathname;try{pathname=decodeURIComponent(url.pathname);}catch{fail('Некорректный адрес');}const path=resolve(publicRoot,'.'+(pathname==='/'?'/index.html':pathname));if(!path.startsWith(publicRoot+sep))fail('Не найдено',404);let info;try{info=await stat(path);}catch{fail('Файл не найден',404);}if(!info.isFile())fail('Файл не найден',404);res.writeHead(200,{'Content-Type':mime[extname(path)]||'application/octet-stream','Cache-Control':pathname.startsWith('/vendor/')?'public,max-age=86400':'no-cache'});res.end(req.method==='HEAD'?undefined:await readFile(path));
   }
  }catch(e){if(res.writableEnded||res.destroyed)return;if(e.closeConnection||!req.complete)res.setHeader('Connection','close');const status=e.status||500;if(status===500)console.error(JSON.stringify({event:'server_error',request_id:requestId,name:e.name}));if(!res.headersSent){if(e.retryAfter)res.setHeader('Retry-After',e.retryAfter);res.writeHead(status,{'Content-Type':'application/json; charset=utf-8'});}res.end(JSON.stringify({error:status===500?'Ошибка сервера':e.message,requestId}));}finally{release?.();doneWork();}
 }));
 server.requestTimeout=Math.max(30000,cfg.http.bodyTimeoutMs+5000);server.headersTimeout=15000;server.keepAliveTimeout=5000;server.maxRequestsPerSocket=1000;
 const cleanup=setInterval(async()=>{
  if(cleanupRunning||draining)return;cleanupRunning=true;const doneWork=work.enter();
  try{db.prepare('DELETE FROM sessions WHERE expires<? OR last_seen<?').run(Date.now(),Date.now()-cfg.idleMs);db.prepare('DELETE FROM positions WHERE updated_at<?').run(Date.now()-3600000);db.prepare('DELETE FROM login_challenges WHERE expires<?').run(Date.now());pruneRateLimits(db,{});await prunePetData(featureStore);await prunePhotoUsage(featureStore);}
  catch(e){console.error(JSON.stringify({event:'cleanup_failed',name:e.name}));}finally{cleanupRunning=false;doneWork();}
 },60000);cleanup.unref();server.on('close',()=>clearInterval(cleanup));
 return {server,db,cfg,audit,beginDrain(){draining=true;},metrics,close(){
  return closing??=(async()=>{draining=true;clearInterval(cleanup);if(server.listening){server.closeIdleConnections();await new Promise((resolve,reject)=>server.close(error=>error?reject(error):resolve()));}await work.idle();if(ownsDb)db.close();})();
 }};
}
export function bootstrapAdmin(db,env=process.env){const email=env.ADMIN_EMAIL,password=env.ADMIN_PASSWORD;if(!email||!password)return null;if(db.prepare("SELECT id FROM users WHERE role='admin'").get())return null;const e=normalizeEmail(email),p=text(password,'ADMIN_PASSWORD',128,12);if(db.prepare('SELECT id FROM users WHERE email=?').get(e))throw new Error('Для существующего аккаунта используйте npm run admin');const uid=id();db.prepare('INSERT INTO users(id,email,name,password,role,created_at) VALUES(?,?,?,?,?,?)').run(uid,e,'Администратор',passwordHash(p),'admin',Date.now());return uid;}
if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url)){
 const app=createApp();const admin=bootstrapAdmin(app.db);if(admin)app.audit(admin,'bootstrap.admin',admin);const port=Number(process.env.PORT||3000),host=process.env.HOST||'127.0.0.1';app.server.listen(port,host,()=>console.log(`City Quest: http://${host}:${port}`));let stopping=false;const shutdown=()=>{if(stopping)return;stopping=true;app.beginDrain();const force=setTimeout(()=>app.server.closeAllConnections(),10000);force.unref();app.close().then(()=>{clearTimeout(force);process.exitCode=0;},()=>{clearTimeout(force);process.exitCode=1;});};process.on('SIGINT',shutdown);process.on('SIGTERM',shutdown);
}
