import assert from 'node:assert/strict';
import {createListRoutes} from '../../src/features/list-routes.mjs';
import {createFeatureStore,run} from '../../src/features/store.mjs';
const decode=value=>JSON.parse(Buffer.from(value,'base64url'));
export async function queryPageScenarios(t,{db,dialect}){
 const cfg={idleMs:1800000,requireAdminMfa:false},store=createFeatureStore({db,dialect,cfg}),route=createListRoutes({store}),now=Date.now();
 const users=['pager-admin','pager-business','pager-player'].map((id,index)=>({id,session_id:id+'-session',role:['admin','business','player'][index]}));
 await store.transaction(function*(){
  for(const user of users){yield run('INSERT INTO users(id,email,name,password,role,created_at) VALUES($1,$2,$3,$4,$5,$6)',[user.id,user.id+'@example.test','Pagingfixture '+user.id,'hash',user.role,now]);yield run('INSERT INTO sessions(token,id,user_id,expires,created_at,last_seen,mfa_verified) VALUES($1,$2,$3,$4,$5,$5,0)',[user.id,user.session_id,user.id,now+3600000,now]);}
  for(let n=0;n<125;n++)yield run('INSERT INTO users(id,email,name,password,role,created_at) VALUES($1,$2,$3,$4,$5,$6)',['pager-user-'+n,`pager-${n}@example.test`,'Pagingfixture user '+n,'hash','player',now]);
  for(let n=0;n<1200;n++){const suffix=String(n).padStart(4,'0');yield run('INSERT INTO organizations(id,owner_id,name,category,lng,lat,status,created_at,city_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)',['pager-org-'+suffix,n%2?users[0].id:users[1].id,'Pagingfixture '+suffix,'cafe',76.9,43.25,'approved',now,'almaty']);yield run('INSERT INTO explored(user_id,cell,created_at,city_id) VALUES($1,$2,$3,$4)',[users[2].id,`${38400+n%40}:${28800+Math.floor(n/40)}`,now,'almaty']);}
  yield run('INSERT INTO explored(user_id,cell,created_at,city_id) VALUES($1,$2,$3,$4)',[users[2].id,'legacy:cell',now,'almaty']);
  for(let n=0;n<240;n++){const suffix=String(n).padStart(4,'0');yield run('INSERT INTO quests(id,owner_id,title,description,lng,lat,radius,xp,scope,verification,status,created_at,city_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)',['pager-quest-'+suffix,users[1].id,'Pagingfixture quest '+suffix,'Pagination fixture',76.879,43.244,100,100,n===239?'personal':'public','token','published',now,'almaty']);if(n!==239)yield run('INSERT INTO completions(user_id,quest_id,xp,created_at) VALUES($1,$2,$3,$4)',[users[2].id,'pager-quest-'+suffix,100,now]);}
 });
 const call=(path,user=users[2],cityId='almaty')=>{const url=new URL(path,'http://localhost');return route({db,cfg,url,path:url.pathname,method:'GET',cityId,user,required:(actor,roles)=>{if(!actor)throw Object.assign(new Error('unauthorized'),{status:401});if(roles&&!roles.includes(actor.role))throw Object.assign(new Error('forbidden'),{status:403});},auth:{publicUser:actor=>({id:actor.id,role:actor.role,xp:actor.xp})}});};
 await store.transaction(function*(){yield run("UPDATE organizations SET name='ҚАЗАҚ ӘЛЕМІ · КОФЕЙНЯ' WHERE id='pager-org-0000'");});
 await t.test('Unicode Cyrillic and Kazakh case folding works in catalog and admin search',async()=>{const result=await call('/api/organizations?q='+encodeURIComponent('қазақ әлемі'));assert.equal(result.items.length,1);assert.equal(result.items[0].id,'pager-org-0000');const admin=await call('/api/manage?search='+encodeURIComponent('кофейня'),users[0]);assert.equal(admin.organizations[0].id,'pager-org-0000');await store.transaction(function*(){yield run("UPDATE organizations SET name='Pagingfixture 0000' WHERE id='pager-org-0000'");});});
 await t.test('catalog cursor visits all rows exactly once and literal wildcard search cannot expand query',async()=>{
  let url='/api/organizations?q=Pagingfixture&limit=113',ids=[];do{const result=await call(url,null);assert.equal(result.total,1200);assert.ok(result.items.length<=113);assert.ok(result.items.every(row=>!Object.hasOwn(row,'owner_id')));ids.push(...result.items.map(row=>row.id));url=result.next_cursor?'/api/organizations?q=Pagingfixture&limit=113&cursor='+result.next_cursor:null;}while(url);
  assert.equal(ids.length,1200);assert.equal(new Set(ids).size,1200);assert.equal((await call('/api/organizations?q=%25',null)).total,0);assert.equal((await call('/api/organizations?q=Pagingfixture&offset=1100',null)).items.length,100);
 });
 await t.test('quest pages preserve completion and unlock state without downloading full exploration history',async()=>{
  const result=await call('/api/quests?q=Pagingfixture&limit=17');assert.equal(result.total,240);assert.equal(result.items.length,17);assert.ok(result.items.every(row=>row.completed&&row.unlocked));assert.ok(result.next_cursor);assert.equal(JSON.stringify(result).includes('code_hash'),false);
  const personal=await call('/api/quests?q=Pagingfixture%20quest%200239');assert.equal(personal.items[0].completed,false);assert.equal(personal.items[0].unlocked,true);assert.equal((await call('/api/quests?q=Pagingfixture%20quest%200239',null)).items[0].unlocked,false);
  let cursor=result.next_cursor,ids=result.items.map(row=>row.id);while(cursor){const next=await call('/api/quests?q=Pagingfixture&limit=17&cursor='+cursor);ids.push(...next.items.map(row=>row.id));cursor=next.next_cursor;}assert.equal(ids.length,240);assert.equal(new Set(ids).size,240);
 });
 await t.test('progress returns exact totals and recoverable bounded pages; viewport excludes malformed legacy cells',async()=>{
  const first=await call('/api/progress?limit=17');assert.equal(first.cells.length,17);assert.equal(first.completed.length,17);assert.equal(first.cells_total,1201);assert.equal(first.completed_total,239);assert.ok(first.cells_next_cursor&&first.completed_next_cursor);
  const next=await call('/api/progress?limit=17&cells_cursor='+first.cells_next_cursor+'&completed_cursor='+first.completed_next_cursor);assert.equal(new Set([...first.cells,...next.cells]).size,34);assert.equal(new Set([...first.completed,...next.completed].map(row=>row.quest_id)).size,34);
  let url='/api/explored?bbox=76.8,43.2,76.8061,43.2031&limit=3',cells=[];do{const result=await call(url);assert.equal(result.total,12);cells.push(...result.cells);url=result.next_cursor?'/api/explored?bbox=76.8,43.2,76.8061,43.2031&limit=3&cursor='+result.next_cursor:null;}while(url);assert.equal(cells.length,12);assert.equal(new Set(cells).size,12);
 });
 await t.test('administration has independent pages, searchable users and strict ownership',async()=>{
  const first=await call('/api/manage?search=Pagingfixture&quest_search=Pagingfixture&user_search=Pagingfixture&limit=17',users[0]);assert.equal(first.organizations.length,17);assert.equal(first.quests.length,17);assert.equal(first.users.length,17);assert.equal(first.pagination.organizations.total,1200);assert.equal(first.pagination.quests.total,240);assert.equal(first.pagination.users.total,128);
  const next=await call('/api/manage?search=Pagingfixture&quest_search=Pagingfixture&user_search=Pagingfixture&limit=17&organizations_cursor='+first.pagination.organizations.next_cursor,users[0]);assert.equal(new Set([...first.organizations,...next.organizations].map(row=>row.id)).size,34);assert.deepEqual(first.quests,next.quests);
  const business=await call('/api/manage?search=Pagingfixture',users[1]);assert.equal(business.organizationTotal,600);assert.ok(business.organizations.every(row=>row.owner_id===users[1].id));assert.deepEqual(business.users,[]);await assert.rejects(call('/api/manage/users',users[1]),{status:403});
  const lookup=await call('/api/manage/users?q=pager-124@example.test',users[0]);assert.equal(lookup.items.length,1);assert.equal(lookup.items[0].id,'pager-user-124');
  const rewards=await call('/api/manage/rewards?limit=17',users[1]);assert.equal(rewards.total,240);assert.equal(rewards.items.length,17);assert.ok(rewards.next_cursor);
 });
 await t.test('token redemption history stays paginated, ownership-scoped and secret-free',async()=>{
  await store.transaction(function*(){for(let n=0;n<121;n++)yield run('INSERT INTO reward_tokens(id,quest_id,issuer_id,token_hash,created_at,expires_at) VALUES($1,$2,$3,$4,$5,$6)',['pager-token-'+String(n).padStart(4,'0'),'pager-quest-0000',users[1].id,'secret-token-hash-'+n,now,now+600000]);});
  let path='/api/manage/quests/pager-quest-0000/redemptions',ids=[];do{const result=await call(path,users[1]);assert.equal(result.total,121);assert.ok(result.items.length<=50);assert.equal(JSON.stringify(result).includes('token_hash'),false);assert.ok(result.items.every(row=>row.state==='active'));ids.push(...result.items.map(row=>row.id));path=result.next_cursor?'/api/manage/quests/pager-quest-0000/redemptions?cursor='+result.next_cursor:null;}while(path);assert.equal(ids.length,121);assert.equal(new Set(ids).size,121);await assert.rejects(call('/api/manage/quests/pager-quest-0000/redemptions',users[2]),{status:403});
 });
 await t.test('cursors cannot cross city, user, search or mode; invalid limits and revoked sessions fail',async()=>{
  const first=await call('/api/quests?q=Pagingfixture&limit=1');await assert.rejects(call('/api/quests?q=Pagingfixture&cursor='+first.next_cursor,users[2],'astana'),{status:400});await assert.rejects(call('/api/quests?q=Pagingfixture&cursor='+first.next_cursor,users[1]),{status:400});await assert.rejects(call('/api/quests?q=different&cursor='+first.next_cursor),{status:400});
  for(const limit of ['0','-1','1.5','Infinity','100000'])await assert.rejects(call('/api/quests?limit='+limit),{status:400});for(const value of ['not-json','!!!!',Buffer.from(JSON.stringify(['wrong-scope',1,'id'])).toString('base64url')])await assert.rejects(call('/api/quests?cursor='+value),{status:400});assert.ok(Array.isArray(decode(first.next_cursor)));
  await store.transaction(function*(){yield run('DELETE FROM sessions WHERE user_id=$1',[users[2].id]);});await assert.rejects(call('/api/progress'),{status:401});
 });
 if(dialect==='sqlite')await t.test('cursor scans use composite indexes instead of temporary sorting',()=>{
  const plans=[['SELECT id FROM organizations WHERE city_id=? AND status=? ORDER BY name,id LIMIT 51',['almaty','approved'],'org_catalog_page'],['SELECT cell FROM explored WHERE user_id=? AND city_id=? AND cell>? ORDER BY cell LIMIT 51',[users[2].id,'almaty','38400:28800'],'explored_page'],['SELECT id FROM users ORDER BY created_at DESC,id DESC LIMIT 51',[],'user_manage_page']];
  for(const [sql,args,index] of plans){const detail=db.prepare('EXPLAIN QUERY PLAN '+sql).all(...args).map(row=>row.detail).join('\n');assert.match(detail,new RegExp(index));assert.doesNotMatch(detail,/TEMP B-TREE/);}
 });
}
